### ISSUE TITLE
Swiftfall and FreeIPA are in Archives

### ISSUE THREAD

**Issue by bmbowdish** [ComputerScienceHouse/blog#33]
In private browsing they are still there.

**Comment by devinmatte** [comment]
They are very much still available on the main page. This is a caching issue.

![screenshot from 2018-03-01 19-50-55](https://user-images.githubusercontent.com/9310513/36877787-eca89fd0-1d89-11e8-9d68-2d8a1b891dc4.png)

**Comment by bmbowdish** [comment]
I still have an issue

I don't know why you closed this
